version: '3'

services:
  vec-server:
    build: .
    ports:
      - "8000:8000"
    environment:
      - VEC_SERVER_PORT=8000
      - VEC_DATABASE_URL=postgres://postgres:postgres@postgres:5432/vecserver?sslmode=disable
      - VEC_REPO_PATH=/data/repos
      - VEC_JWT_SECRET=vec-server-secret-key
    volumes:
      - ./data:/data
    depends_on:
      - postgres
    restart: unless-stopped

  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=vecserver
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres-data: 